services:
  authms_api:
    build:
      context: .
      dockerfile: src/AuthMS.Api/Dockerfile
    container_name: authms_api
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: 'Server=${MYSQL_HOST:-host.docker.internal};Port=${MYSQL_PORT:-3306};Database=${MYSQL_DATABASE:-hygea_auth};User Id=${MYSQL_USER:-hygea};Password=${MYSQL_PASSWORD:-change-me};SslMode=${MYSQL_SSL_MODE:-Preferred};'

      Integrations__DirectoryMS__BaseUrl: "http://host.docker.internal:8081/api/"
      JwtSettings__key: ${JWT_KEY:-dev-super-secret-key-change-me}
      JwtSettings__issuer: ${JWT_ISSUER:-CuidarMed}
      JwtSettings__audience: ${JWT_AUDIENCE:-CuidarMed}
      JwtSettings__expiresInMinutes: ${JWT_EXPIRES_IN_MINUTES:-60}
      EmailSettings__SmtpServer: ${EMAIL_SMTP_SERVER:-mail.hygeagroup.com.ar}
      EmailSettings__SmtpPort: ${EMAIL_SMTP_PORT:-465}
      EmailSettings__SenderEmail: ${EMAIL_SENDER_EMAIL:-notificaciones@hygeagroup.com.ar}
      EmailSettings__SenderPassword: ${EMAIL_SENDER_PASSWORD}
      EmailSettings__EnableEmails: ${EMAIL_ENABLE_EMAILS:-false}
    ports:
      - "8082:8080"
    networks:
      - cuidarmed_new_net

networks:
  cuidarmed_new_net:
    external: true
